### ISSUE TITLE
Levantamento de informações

### ISSUE THREAD

**Issue by jtemporal** [pythonsudeste/pythonsudeste_documentacao#1]
Precisamos levantar as informações do evento de 2016 e 2017

**Comment by biancarosa** [comment]
@jtemporal consigo ajudar com as de 2017

**Comment by jtemporal** [comment]
opa @biancarosa manda por aqui mesmo!

**Comment by jtemporal** [comment]
## Edição de 2016

2 e 3 de Setembro

**Locais**
??

**Números**
- ~140 inscritos
- ~117 participantes
- 4 keynotes
- 8 palestras
- 7 tutoriais

**Keynotes**
- Alê Borba
- Mirella Moro
- Luciano Ramalho
- Larissa Lautert

**Participação feminina**
- keynotes: 50%
- palestras: ~30%

**Organizadores**
- Cássio Botaro
- Ervilis
- Igor Santos
- Igor Leroy
- Raphael Passini
- Tiago Guimarães
- Turicas
- Julio

**Links**:
- Fotos: https://drive.google.com/drive/folders/0B4fDi1iT_FA3akRKYkVvdXNZM1U?usp=sharing

gracias @cassiobotaro <3

**Comment by berinhard** [comment]
## Edição de 2017

05 e 06 de Maio de 2017

**Locais**
- Palestras: Auditório do Clube de Engenharia 
- Tutoriais: Universidade Veiga de Almeida 

**Números**
- 326 inscritos
- 234 participantes
- 3 keynotes
- 9 palestras
- Valor total arrecadado: **R$ 39.316,67**
- Valor total do evento: **R$ 40.693,97**

**Keynotes**
- Claudio Berrondo
- Álvaro "Turicas"
- Annanda Souza

**Participação feminina**
- 1/3 dos keynotes (33%)
- 2/9 das palestras (22%)
- 49/234 participantes (21%)

**Organizadores**
- Bernardo Fontes
- Bianca Rosa
- Eduardo Stalinho
- James Peres (saudades inclusive)
- Julia Kastrup
- Mariana Bedran
- Paula Grangeiro
- Raffael Tancman
- Raysa Dutra
- Thais Viana

**Inovações**
- Primeiro evento com votação anônima dos autores das palestras

**Links**:
- Fotos: https://www.facebook.com/pg/pythonsudeste/photos/?tab=album&album_id=303043140123523
- Filmagens: https://www.youtube.com/watch?v=8Lejr3KZIfk&list=PLA-HOyS1nFHd3Ui4fSuDGhgsie8TD8nK0

**Comment by berinhard** [comment]
@biancarosa pode deixar que já levantei os dados aqui =)

**Comment by maribedran** [comment]
Pode resolver a issue?
